### ISSUE TITLE
Update crates.io documentation

### ISSUE THREAD

**Issue by mplsgrant** [srishanbhattarai/geoutils#10]
The current creates.io documentation at https://crates.io/crates/geoutils shows the following code in the Vincenty's Inverse Formula example

```println!("Distance = {}", distance);```

Instead in should read:

````println!("Distance = {}", distance.meters());````

**Comment by srishanbhattarai** [comment]
Thank you for reporting!

Published alongside some other changes in [0.4.0](https://github.com/srishanbhattarai/geoutils/releases/tag/0.4.0)

Links:
1. [crates.io](https://crates.io/crates/geoutils)
2. [docs.rs](https://docs.rs/geoutils/0.4.0/geoutils/)
