### ISSUE TITLE
Feature request: WGS84 altitude to barometric altitude conversion

### ISSUE THREAD

**Issue by baarkerlounger** [srishanbhattarai/geoutils#19]
GPS devices seem to typically return locations with altitude measured relative to the WGS84 ellipsoid rather than sea level. Would an algorithm to convert between them be a good fit for this library?

https://stackoverflow.com/questions/22196714/wgs84-geoid-height-altitude-offset-for-external-gps-data-on-ios

**Comment by srishanbhattarai** [comment]
Unfortunately I lack the time to work on this project or look into feature requests / issues. I plan to archive this repository soon.
